name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup
        shell: bash
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake $GITHUB_WORKSPACE
          cmake --build . 2> >(tee "output.txt")
      - name: Post PR comment for warnings/errors
        if: always()
        uses: JacobDomagala/CompileResult@master
        with:
          comment_title: UBUNTU COMPILE RESULT
          compile_result_file: ${{runner.workspace}}/build/output.txt
