name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - kaan_workspace

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Post warnings/errors as PR comment
        uses: JacobDomagala/CompileResult@master
        with:
          comment_title: UBUNTU COMPILE RESULT
          compile_result_file: ${{runner.workspace}}/build/output.txt

      - name: Install g++
        run: sudo apt-get -y install g++

      - name: Build C++ code
        run: g++ -Wall -c main.cpp -o main.o && g++ main.o -o main

      - name: Capture and display warnings
        run: g++ -Wall -Wunused-variable main.cpp -o main 2> >(tee "warnings.txt")

      - name: Show warnings
        run: cat warnings.txt
        
      - name: Count warnings
        run: |
          echo "Total Warnings: $(grep -c 'warning:' warnings.txt)"
