name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - kaan_workspace

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get -y install g++

    - name: Build C++ code
      run: g++ -Wall -c main.cpp -o main.o && g++ main.o -o main

    - name: Capture and display warnings
      run: g++ -Wall -Wunused-variable main.cpp -o main 2> warnings.txt

    - name: Show warnings
      run: cat warnings.txt

