name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get -y install g++

    - name: Build C++ code
      run: g++ -Wall -c main.cpp -o main.o

    - name: Compile C++ code
      run: g++ -Wall -Wunused-variable main.cpp -o main 2> warnings.txt


    - name: Show warnings
      run: cat warnings.txt
      
    - name: Count warnings
      run: |
        echo "Total Warnings: $(grep -c 'warning:' warnings.txt)"

