name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git for Windows
      run: |
        choco install git -y --params "/GitAndUnixToolsOnPath /NoAutoCrlf"

    - name: Set up Git Bash environment
      shell: bash
      run: |
        export MSYS_NO_PATHCONV=1
        export MSYS2_PATH_TYPE=inherit
        export PATH="/usr/bin:$PATH"
        echo ::add-path::/usr/bin

    - name: Install GCC
      run: |
        pacman --noconfirm -S mingw-w64-x86_64-gcc

    - name: Build C++ code
      run: g++ -Wall -c main.cpp -o main.o && g++ main.o -o main

    - name: Capture and display warnings
      run: g++ -Wall -fsyntax-only main.cpp 2>&1 | grep 'warning' || true
