name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Post warnings/errors as PR comment
      uses: JacobDomagala/CompileResult@v0.0.2



